# Site
name: 'Fora da Bolha'
description: 'Esta é a nossa tentativa de pôr um pé fora da bolha.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/foradabolha.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'geral@foradabolha.pt'
mailchimp-list: 'https://foradabolha.us1.list-manage.com/subscribe/post?u=555cdcf38ad1e128145f9cfa2&amp;id=c8f76676fa'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

edicao:
    abr21:
      link:           abril-2021
      name:           "Polarização"
      date:           "Abril de 2021"
      image:          assets/images/covers/abr21.png
      description:    "Em estilo de introdução, a primeira edição é dedicada ao tema da polarização. Vivemos num mundo polarizado? As bolhas em que vivemos estão mais fechadas do que nunca? O que causa fenómenos de polarização? Como é que ela se manifesta na política e na sociedade? A polarização é uma coisa má?"

    jul21:
      link:           julho-2021
      name:           "Ciência e Tecnologia"
      date:           "Julho de 2021"
      image:          assets/images/covers/jun21.png
      description:    "No último ano, todos viramos os olhos para a ciência à procura de explicações e de soluções para os nossos maiores problemas. Dedicamos esta edição aos vários desafios presentes e futuros da ciência e da sua útil companheira, a tecnologia. Desde as condições de trabalho dos investigadores às levantadas pela inteligência artificial."

authors:
    equipa:
      name:           Equipa FB
      link:           equipa
      site:           https://www.foradabolha.pt/sobre
      avatar:         assets/images/logo.png
      bio:            "Autor para publicação de posts gerais."
      email:          geral@foradabolha.pt
      social:        https://twitter.com/foradabolhablog

    cesarcaldeira:
      name:           César Caldeira
      link:           cesar-caldeira
      social:         https://linkedin.com/in/cesarmcs
      avatar:         assets/images/authors/cesarcaldeira.jpeg
      bio:            "Lisboeta de costela Arganilense. Finalista de ciência política e relações internacionais ao fim de três anos a descobrir o mundo do design de jogos, engenharia informática e do associativismo académico. Recentemente obcecado com xadrez. Eternamente viciado em chá. Militante da Juventude Social Democrata."

    anareis:
      name:           Ana Reis
      social:         https://twitter.com/AACarvalhoReis
      link:           ana-reis
      avatar:         assets/images/authors/anareis.jpg
      bio:            "Curiosa sobre o mundo, as pessoas e as suas ideias. De momento, estudante de Matemática no Instituto Superior Técnico."

    fredericocarvalho:
      name:           Frederico Carvalho
      link:           frederico-carvalho
      avatar:         assets/images/authors/fredericocarvalho.jpg
      bio:            "Licenciado em Filosofia e mestrando em Filosofia Política na FCSH-UNL. Almadense insatisfeito por natureza e de uma esquerda naturalmente insatisfeita."

    pedrosilva:
      name:           Pedro Silva
      link:           pedro-silva
      avatar:         assets/images/authors/pedrosilva.jpg
      bio:            "Estudante de matemática, pessoa de esquerda e passageiro frequente de cacilheiros. Nenhuma habilitação para escrever sobre política, mas tento na mesma."

    giloliveira:
      name:           Gil Oliveira
      link:           gil-oliveira
      avatar:         assets/images/authors/giloliveira.jpg
      bio:            "Descrição do Gil"


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: equipa
      comments: false

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
