# Site
name: 'Fora da Bolha'
description: 'Esta é a descrição do nosso pequeno site. Still working on things.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/foradabolha.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'geral@foradabolha.pt'
mailchimp-list: 'https://foradabolha.us1.list-manage.com/subscribe/post?u=555cdcf38ad1e128145f9cfa2&amp;id=c8f76676fa'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

edicao:
    abr20:
      link:           abril-2020
      name:           "Polarização"
      date:           "Abril de 2020"
      image:          assets/images/covers/abr20.jpg
      description:    "Esta edição é sobre a polarização. Go figure. Este texto é só um exemplo de como ficaria a descrição de uma dada edição. Pode estar aqui escrito o que quisermos, I guess."


authors:
    equipa:
      name:           Equipa FB
      link:           equipa
      site:           https://www.foradabolha.pt/sobre
      avatar:         assets/images/logo.jpg
      bio:            "Autor para publicação de posts gerais."
      email:          geral@foradabolha.pt
      twitter:        https://twitter.com/foradabolhablog
      facebook:       https://facebook.com/foradabolha.pt

    cesarcaldeira:
      name:           César Caldeira
      link:           cesar-caldeira
      site:           linkedin.com/in/cesarmcs
      avatar:         assets/images/authors/cesarcaldeira.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

    anareis:
      name:           Ana Reis
      link:           ana-reis
      avatar:         assets/images/authors/anareis.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

    evandrobreia:
      name:           Evandro Breia
      link:           evandro-breia
      avatar:         assets/images/authors/evandrobreia.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

    fredericocarvalho:
      name:           Frederico Carvalho
      link:           frederico-carvalho
      avatar:         assets/images/logo.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

    pedrosilva:
      name:           Pedro Silva
      link:           pedro-silva
      avatar:         assets/images/logo.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

    beatrizrosado:
      name:           Beatriz Rosado
      link:           beatriz-rosado
      avatar:         assets/images/logo.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: equipa
      comments: false

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
