# Site
name: 'Fora da Bolha'
description: 'Esta é a descrição do nosso pequeno site. Still working on things.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'geral@foradabolha.pt'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    cesarcaldeira:
      name:           César Caldeira
      site:           https://www.wowthemes.net
      avatar:         assets/images/authors/cesarcaldeira.jpg
      bio:            "Estudante de ciência política e relações internacionais na Universidade Católica Portuguesa. Ex-aluno de engenharia informática na FCUL e Sheffield Hallam University. Gosta de chá."
      email:          cesar.caldeira@foradabolha.pt
      twitter:        https://twitter.com/wowthemesnet

    anareis:
      name:           Ana Reis
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "Estudante de matemática no Instituto Superior Técnico. Estudou na Universidade de Bristol. Gosta de chá."
      email:          ana.reis@foradabolha.pt
      twitter:        https://twitter.com/wowthemesnet

    beatrizrosado:
      name:           Beatriz Rosado
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "Estudante de ciência política e relações internacionais na Universidade Católica Portuguesa. Ex-aluna de direito na Universidade Nova de Lisboa. Não gosta de chá."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
