# Site
name: 'Fora da Bolha'
description: 'Esta é a descrição do nosso pequeno site. Still working on things.'
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/foradabolha.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'geral@foradabolha.pt'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    equipa:
      name:           Equipa FB
      site:           https://www.foradabolha.pt/sobre
      avatar:         assets/images/logo.jpg
      bio:            "Autor para publicação de posts gerais"
      email:          geral@foradabolha.pt
      twitter:        https://twitter.com/wowthemesnet
      facebook:       https://twitter.com/wowthemesnet

    cesarcaldeira:
      name:           César Caldeira
      site:           https://www.wowthemes.net
      avatar:         assets/images/authors/cesarcaldeira.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."
      email:          cesar.caldeira@foradabolha.pt
      twitter:        https://twitter.com/wowthemesnet

    anareis:
      name:           Ana Reis
      site:           https://www.wowthemes.net
      avatar:         assets/images/authors/anareis.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."
      email:          ana.reis@foradabolha.pt
      twitter:        https://twitter.com/wowthemesnet

    evandrobreia:
      name:           Evandro Breia
      site:           https://www.wowthemes.net
      avatar:         assets/images/authors/evandrobreia.jpg
      bio:            "Descrição lorem ipsum. Algo interessante aqui. Isto é um teste."
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
